/*
/TABELA UŻYTKOWNIKÓW SERWISU
*/

CREATE TABLE T_USERS (
    /*ID UŻYTKOWNIKA AUTOINCREMENT*/
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    
    /*LOGIN UŻYTKOWNIKA, UNIKALNY*/
    LOGIN       VARCHAR2(32) UNIQUE NOT NULL,
    
    /*HASŁO UŻYTKOWNIKA JAKO HASH*/
    PASS    VARCHAR2(255) NOT NULL,
    
    /*EMAIL UŻYTKOWNIKA, UNIKALNY*/
    EMAIL       VARCHAR2(64) UNIQUE NOT NULL,
    
    /*DATA URODZENIA UŻYTKOWNIKA*/
    BDATE       DATE NOT NULL,
    
    /*DATA UTWORZENIA KONTA UŻYTKOWNIKA*/
    CDATE       DATE NOT NULL,
    
    /*DATA I CZAS OSTATNIEGO LOGOWANIA UŻYTKOWNIKA*/
    LAST_LOG    DATE NOT NULL,
    
    /*STATUS KONTA UŻYTKOWNIKA
    /1 - NIEAKTYWOWANE
    /2 - AKTYWOWANE
    /3 - ZAWIESZONE
    /4 - USUNIĘTE
    */
    STATUS      NUMBER NOT NULL,
    
    /*ROLA UŻYTKOWNIKA
    /1 - SZARAK
    /2 - ADMIN
    /3 - DEV
    */
    USR_ROLE    NUMBER NOT NULL
);